name: tutorial

description: "Draw over an Image in Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.8
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  get_it: ^7.7.0
  provider: ^6.1.2
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  flutter_lints: ^4.0.0

import_sorter:
  emojis: true
  comments: false
  ignored_files:
    - \/test\/*

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/png_images/
    - assets/svg_icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins-black.ttf
          weight: 900
        - asset: assets/fonts/poppins-extra-bold.ttf
          weight: 800
        - asset: assets/fonts/poppins-bold.ttf
          weight: 700
        - asset: assets/fonts/poppins-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/poppins-medium.ttf
          weight: 500
        - asset: assets/fonts/poppins-regular.ttf
          weight: 400
        - asset: assets/fonts/poppins-light.ttf
          weight: 300
        - asset: assets/fonts/poppins-extra-light.ttf
          weight: 200
        - asset: assets/fonts/poppins-thin.ttf
          weight: 100